name: figma_corrector
description: Figma Corrector is a tool that helps to correct the figma flutter file to be ready for the development.
version: 0.0.1
# repository: https://github.com/my_org/my_repo
publish_to: none

executables:
  figma_corrector:

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

  utils:
    git:
      url: https://github.com/altynbek132/flutter_util_packages
      path: packages/utils

  change_case: ^2.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
